### ISSUE TITLE
WatchConnectivityに関する質問

### ISSUE THREAD

**Issue by DevUNakamura** [koogawa/WatchConnectivitySample#1]
突然のご連絡申し訳ございません。

Apple Watch ⇔ iPhone間のデータのやりとりの実装をしているのですが、一点質問がございます。
iPhone側のアプリが未起動(プロセスにもない状態)の場合、Apple WatchからiPhoneのデータを受け取ることは可能なのでしょうか？
もしご存知でしたらご教授いただきたく思っています。
何卒よろしくおねがいします。

**Comment by koogawa** [comment]
こんにちは。しばらくWatchConnectivityを触っていないので推測になってしまいますが、アップルのドキュメント
https://developer.apple.com/documentation/watchconnectivity に

> Most transfers happen in the background when the receiving app is inactive. When the app wakes up, it is notified of any data that arrived while it was inactive.

と記載があるように、iPhone側は少なくともbackground状態であることが必要だと思われます。
つまり、iPhone側のアプリが未起動(プロセスにもない状態)の場合、Apple WatchからiPhoneのデータを受け取ることは難しいと予想します。

もし、完全な回答が必要であればQ&Aサイトで質問されることをおすすめします 🙏

**Comment by koogawa** [comment]
Closing. Please reopen if still an issue
